### ISSUE TITLE
Looking to work on Tasks

### ISSUE THREAD

**Issue by manikantanune1990** [bwisegithub/music-discoverer#8]
Hey,

I am a starter in AngularJS and learning things on codecademy and codeschool. I would like to work on real time project like this. Can you assign me some tasks. I don't know where to communicate with you so I am creating a open task here. Sorry if it mislead you.

Thanks

**Comment by bwisegithub** [comment]
Hi @manikantanune1990,

This is just a project for me to learn AngularJS as well, so I'm not looking to collaborate at this time.  I appreciate your interest and wish you luck.   I look forward to seeing your projects.
